import asyncio
import aiohttp
import time

async def check_domain(session, domain, semaphore):
    # Try both HTTPS and HTTP
    urls = [f"https://{domain}", f"http://{domain}"]
    
    async with semaphore:
        for url in urls:
            try:
                # We use a 7-second timeout so we don't get stuck on dead IPs
                async with session.get(url, timeout=7, ssl=False, allow_redirects=True) as response:
                    if response.status < 400: # Any 2xx or 3xx status means a server is there
                        print(f"[+] ALIVE: {url} (Status: {response.status})")
                        return url
            except Exception:
                continue
    return None

async def run_checker(input_file, output_file, max_concurrent=100):
    print(f"[*] Loading domains from {input_file}...")
    
    try:
        with open(input_file, 'r') as f:
            domains = [line.strip() for line in f if line.strip()]
    except FileNotFoundError:
        print(f"[!] Could not find {input_file}")
        return

    print(f"[*] Starting alive check for {len(domains)} domains...")
    print(f"[*] Concurrency set to {max_concurrent} simultaneous checks.")
    
    semaphore = asyncio.Semaphore(max_concurrent)
    alive_urls = []
    
    # Use a custom User-Agent to look like a normal browser
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
    
    start_time = time.time()
    
    async with aiohttp.ClientSession(headers=headers) as session:
        tasks = [check_domain(session, domain, semaphore) for domain in domains]
        results = await asyncio.gather(*tasks)
        
        # Filter out None results
        alive_urls = [url for url in results if url]

    # Save the results
    with open(output_file, 'w') as f:
        for url in sorted(alive_urls):
            f.write(f"{url}\n")
            
    elapsed = time.time() - start_time
    print("-" * 40)
    print(f"[=] Scan Complete in {elapsed:.2f} seconds.")
    print(f"[=] Found {len(alive_urls)} LIVE websites out of {len(domains)} total domains.")
    print(f"[=] Results saved to {output_file}")

if __name__ == "__main__":
    # Point this to the file generated by your Subfinder/Amass script
    INPUT_LIST = "recursive_gov_bd_domains.txt"
    OUTPUT_LIST = "crawled_alive_gov_bd_sites.txt"
    
    # 100 concurrent requests is a good balance of speed without crashing your router
    asyncio.run(run_checker(INPUT_LIST, OUTPUT_LIST, max_concurrent=100))


# install it via go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest 
# and run: cat discovered_domains.txt |
#  httpx -title -tech-detect -status-code